
GET http://localhost:5095
###
GET http://localhost:5095/campaigns
### 
POST http://localhost:5095/rpgsystem
Content-Type: application/json

{
  "name": "Dungeons & Dragons",
  "shortName": "DnD 5e",
  "description": "The most popular RPG system"
}

### 
POST http://localhost:5095/campaigns
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Curse of Strahd",
  "rpgSystemId": 1,
  "description": "Vampires"
}
###
GET http://localhost:5095/rpgsystem
### 
POST http://localhost:5095/register
Content-Type: application/json

{
  "email": "test@user.pl",
  "password": "P@ssword123"
}
###
POST http://localhost:5095/login
Content-Type: application/json

{
"email": "test@user.pl",
"password": "P@ssword123"
}
###
POST http://localhost:5095/campaigns/9/members
Content-Type: application/json

{
  "userId": "fc5addf2-fd38-4081-b35d-8c5932aac9ce",
  "UserType": 1
}
###
GET http://localhost:5095/campaigns/9/members/10
